version: '3.8'
services:
  database:
    image: postgres:15.3-alpine
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=erikp
      - POSTGRES_DATABASE=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - 4000:4000
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - 8080:3000
    depends_on:
      - backend
    stdin_open: true
volumes:
  database:
    driver: local
