version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - 4000:4000
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - 3000:8080
    depends_on:
      - backend
    stdin_open: true
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=erikp
      - POSTGRES_DB=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
